name: primeiro-pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest

    steps:
      - name: "Minha primeira ação"
        run: echo "hello world !!!"

      - name: "Segunda ação"
        run: |
          echo "Você criou seu primeiro Workflow"
          echo "Parabéns"

  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest

    steps:
      - name: "Verificação do NodeJS atual"
        run: node --version

      - name: "Definição da versão 18.x do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: "Verificação da versão do NodeJS depois de instalar"
        run: node --version
