name: primeiro-pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest

    steps:
      - name: "Minha primeira ação"
        run: echo "hello world !!!"

      - name: "Segunda ação"
        run: |
          echo "Você criou seu primeiro Workflow"
          echo "Parabéns"

  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest

    steps:
      - name: "Verificação do NodeJS atual"
        run: node --version
